    # Docker System Prune
    - name: Prune Docker (containers, images, networks, volumes)
      community.docker.docker_prune:
        containers: true
        images: true
        networks: true
        volumes: true
        builder_cache: true
      register: docker_prune_ouput
    - name: Prune Docker Output
      debug:
        var: docker_prune_ouput

